//! Deterministic, invertible floor-symbol operator catalog for the Omega codec.
//!
//! This module deliberately separates two provenance classes:
//!
//! * operators 0..=7 preserve the inherited C2^3 R/N/Q algebra, reproducing
//!   its 8-bit views exactly from `pais_omega_floor1.rs`; 6/10/12-bit symbols
//!   use the specified same-width half-swap/per-half-bit-reverse extension;
//! * operators 8..=39 are newly specified computational byte permutations.
//!
//! The sector and radial/lens names describe software coordinate transforms.
//! They make no claim about physical sectors, lenses, cosmology, or quantum
//! behavior.

use std::error::Error;
use std::fmt;

pub const OPERATOR_COUNT: usize = 40;
pub const RNQ_COUNT: usize = 8;
pub const SECTOR_COUNT: usize = 12;
pub const LENS_COUNT: usize = 20;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Family {
    RnqC2xC2xC2,
    SectorCyclic,
    RadialLens,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Provenance {
    /// Inherited operator algebra; exact existing realization at 8 bits.
    InheritedExact,
    /// A new, explicitly specified computational transform.
    NewComputational,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OperatorSpec {
    pub id: u8,
    pub name: &'static str,
    pub family: Family,
    pub provenance: Provenance,
    pub inverse_id: u8,
}

macro_rules! op {
    ($id:expr, $name:expr, $family:ident, $provenance:ident, $inverse:expr) => {
        OperatorSpec {
            id: $id,
            name: $name,
            family: Family::$family,
            provenance: Provenance::$provenance,
            inverse_id: $inverse,
        }
    };
}

/// Canonical operator order. IDs are stable serialization values.
pub const OPERATORS: [OperatorSpec; OPERATOR_COUNT] = [
    // Exact C2^3 orbit generated by commuting involutions R, N, and Q.
    op!(0, "RNQ_I_000", RnqC2xC2xC2, InheritedExact, 0),
    op!(1, "RNQ_R_001", RnqC2xC2xC2, InheritedExact, 1),
    op!(2, "RNQ_N_010", RnqC2xC2xC2, InheritedExact, 2),
    op!(3, "RNQ_RN_011", RnqC2xC2xC2, InheritedExact, 3),
    op!(4, "RNQ_Q_100", RnqC2xC2xC2, InheritedExact, 4),
    op!(5, "RNQ_RQ_101", RnqC2xC2xC2, InheritedExact, 5),
    op!(6, "RNQ_NQ_110", RnqC2xC2xC2, InheritedExact, 6),
    op!(7, "RNQ_RNQ_111", RnqC2xC2xC2, InheritedExact, 7),
    // Twelve TRI12 directions d=0..11. Each rotates each <=12-byte chunk
    // left by d modulo that chunk's actual length; inverse rotates right.
    op!(8, "TRI12_D00", SectorCyclic, NewComputational, 8),
    op!(9, "TRI12_D01", SectorCyclic, NewComputational, 9),
    op!(10, "TRI12_D02", SectorCyclic, NewComputational, 10),
    op!(11, "TRI12_D03", SectorCyclic, NewComputational, 11),
    op!(12, "TRI12_D04", SectorCyclic, NewComputational, 12),
    op!(13, "TRI12_D05", SectorCyclic, NewComputational, 13),
    op!(14, "TRI12_D06", SectorCyclic, NewComputational, 14),
    op!(15, "TRI12_D07", SectorCyclic, NewComputational, 15),
    op!(16, "TRI12_D08", SectorCyclic, NewComputational, 16),
    op!(17, "TRI12_D09", SectorCyclic, NewComputational, 17),
    op!(18, "TRI12_D10", SectorCyclic, NewComputational, 18),
    op!(19, "TRI12_D11", SectorCyclic, NewComputational, 19),
    // One gather direction per canonical icosahedron face. Each has an
    // explicitly computed scatter inverse under the same stable face ID.
    op!(20, "PI20_FACE_00", RadialLens, NewComputational, 20),
    op!(21, "PI20_FACE_01", RadialLens, NewComputational, 21),
    op!(22, "PI20_FACE_02", RadialLens, NewComputational, 22),
    op!(23, "PI20_FACE_03", RadialLens, NewComputational, 23),
    op!(24, "PI20_FACE_04", RadialLens, NewComputational, 24),
    op!(25, "PI20_FACE_05", RadialLens, NewComputational, 25),
    op!(26, "PI20_FACE_06", RadialLens, NewComputational, 26),
    op!(27, "PI20_FACE_07", RadialLens, NewComputational, 27),
    op!(28, "PI20_FACE_08", RadialLens, NewComputational, 28),
    op!(29, "PI20_FACE_09", RadialLens, NewComputational, 29),
    op!(30, "PI20_FACE_10", RadialLens, NewComputational, 30),
    op!(31, "PI20_FACE_11", RadialLens, NewComputational, 31),
    op!(32, "PI20_FACE_12", RadialLens, NewComputational, 32),
    op!(33, "PI20_FACE_13", RadialLens, NewComputational, 33),
    op!(34, "PI20_FACE_14", RadialLens, NewComputational, 34),
    op!(35, "PI20_FACE_15", RadialLens, NewComputational, 35),
    op!(36, "PI20_FACE_16", RadialLens, NewComputational, 36),
    op!(37, "PI20_FACE_17", RadialLens, NewComputational, 37),
    op!(38, "PI20_FACE_18", RadialLens, NewComputational, 38),
    op!(39, "PI20_FACE_19", RadialLens, NewComputational, 39),
];

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct UnknownOperator(pub u8);

impl fmt::Display for UnknownOperator {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "unknown Omega operator id {}", self.0)
    }
}

impl Error for UnknownOperator {}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SymbolTransformError {
    UnknownOperator(u8),
    InvalidFloorBits(u8),
    SymbolOutOfRange { index: usize, value: u16, bits: u8 },
}

impl fmt::Display for SymbolTransformError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match *self {
            Self::UnknownOperator(id) => write!(f, "unknown Omega operator id {id}"),
            Self::InvalidFloorBits(bits) => {
                write!(f, "invalid floor width {bits}; expected one of 6,8,10,12")
            }
            Self::SymbolOutOfRange { index, value, bits } => write!(
                f,
                "symbol {value} at index {index} is outside the {bits}-bit floor"
            ),
        }
    }
}

impl Error for SymbolTransformError {}

pub fn operator_spec(id: u8) -> Result<&'static OperatorSpec, UnknownOperator> {
    OPERATORS.get(id as usize).ok_or(UnknownOperator(id))
}

fn validate_symbols(bits: u8, input: &[u16]) -> Result<(), SymbolTransformError> {
    if !matches!(bits, 6 | 8 | 10 | 12) {
        return Err(SymbolTransformError::InvalidFloorBits(bits));
    }
    let limit = 1_u16 << bits;
    for (index, value) in input.iter().copied().enumerate() {
        if value >= limit {
            return Err(SymbolTransformError::SymbolOutOfRange { index, value, bits });
        }
    }
    Ok(())
}

/// Floor-native API. Values are symbols, not packed bytes.
pub fn apply_symbols(
    id: u8,
    bits: u8,
    input: &[u16],
) -> Result<Vec<u16>, SymbolTransformError> {
    operator_spec(id).map_err(|_| SymbolTransformError::UnknownOperator(id))?;
    validate_symbols(bits, input)?;
    Ok(match id {
        0..=7 => apply_rnq_symbols(id, bits, input),
        8..=19 => apply_sector_symbols(id, input),
        20..=39 => apply_lens_symbols(id, input),
        _ => unreachable!("operator_spec rejected the id"),
    })
}

/// Floor-native inverse. PI20 and TRI12 use explicit computed scatters.
pub fn invert_symbols(
    id: u8,
    bits: u8,
    input: &[u16],
) -> Result<Vec<u16>, SymbolTransformError> {
    let spec = operator_spec(id).map_err(|_| SymbolTransformError::UnknownOperator(id))?;
    validate_symbols(bits, input)?;
    Ok(match id {
        8..=19 => invert_sector_symbols(id, input),
        20..=39 => invert_lens_symbols(id, input),
        _ => apply_rnq_symbols(spec.inverse_id, bits, input),
    })
}

/// 8-bit compatibility wrapper over the floor-native symbol API.
pub fn apply_operator(id: u8, input: &[u8]) -> Result<Vec<u8>, UnknownOperator> {
    operator_spec(id)?;
    let symbols = input.iter().map(|value| *value as u16).collect::<Vec<_>>();
    let output = apply_symbols(id, 8, &symbols).expect("u8 values are valid 8-bit symbols");
    Ok(output.into_iter().map(|value| value as u8).collect())
}

/// 8-bit compatibility inverse over the floor-native symbol API.
pub fn invert_operator(id: u8, input: &[u8]) -> Result<Vec<u8>, UnknownOperator> {
    operator_spec(id)?;
    let symbols = input.iter().map(|value| *value as u16).collect::<Vec<_>>();
    let output = invert_symbols(id, 8, &symbols).expect("u8 values are valid 8-bit symbols");
    Ok(output.into_iter().map(|value| value as u8).collect())
}

// ---- Inherited exact C2^3 R/N/Q transforms -------------------------------

fn t_r_symbols(input: &[u16]) -> Vec<u16> {
    input.iter().rev().copied().collect()
}

fn t_n_symbols(bits: u8, input: &[u16]) -> Vec<u16> {
    let half = bits / 2;
    let half_mask = (1_u16 << half) - 1;
    input
        .iter()
        .map(|symbol| ((symbol & half_mask) << half) | ((symbol >> half) & half_mask))
        .collect()
}

fn reverse_low_bits(mut value: u16, width: u8) -> u16 {
    let mut reversed = 0_u16;
    for _ in 0..width {
        reversed = (reversed << 1) | (value & 1);
        value >>= 1;
    }
    reversed
}

fn t_q_symbols(bits: u8, input: &[u16]) -> Vec<u16> {
    let half = bits / 2;
    let half_mask = (1_u16 << half) - 1;
    input
        .iter()
        .map(|symbol| {
            (reverse_low_bits(symbol >> half, half) << half)
                | reverse_low_bits(symbol & half_mask, half)
        })
        .collect()
}

/// Floor-native extension of exact `geometry_view`: R bit 0, N bit 1, Q bit 2.
fn apply_rnq_symbols(mask: u8, bits: u8, input: &[u16]) -> Vec<u16> {
    let mut output = input.to_vec();
    if mask & 1 != 0 {
        output = t_r_symbols(&output);
    }
    if mask & 2 != 0 {
        output = t_n_symbols(bits, &output);
    }
    if mask & 4 != 0 {
        output = t_q_symbols(bits, &output);
    }
    output
}

// ---- New 12-sector computational transforms ------------------------------

fn apply_sector_symbols(id: u8, input: &[u16]) -> Vec<u16> {
    let mut output = input.to_vec();
    let direction = (id - 8) as usize;
    for chunk in output.chunks_mut(12) {
        if !chunk.is_empty() {
            let shift = direction % chunk.len();
            chunk.rotate_left(shift);
        }
    }
    output
}

fn invert_sector_symbols(id: u8, input: &[u16]) -> Vec<u16> {
    let mut output = input.to_vec();
    let direction = (id - 8) as usize;
    for chunk in output.chunks_mut(12) {
        if !chunk.is_empty() {
            let shift = direction % chunk.len();
            chunk.rotate_right(shift);
        }
    }
    output
}

// ---- New PI-20 / icosahedron-face computational transforms ---------------

/// Canonical icosahedron topology: 12 vertex IDs and 20 triangular faces.
/// Geometry is not needed; shared vertex pairs define face adjacency exactly.
pub const ICOSAHEDRON_FACES: [[u8; 3]; 20] = [
    [0, 11, 5], [0, 5, 1], [0, 1, 7], [0, 7, 10], [0, 10, 11],
    [1, 5, 9], [5, 11, 4], [11, 10, 2], [10, 7, 6], [7, 1, 8],
    [3, 9, 4], [3, 4, 2], [3, 2, 6], [3, 6, 8], [3, 8, 9],
    [4, 9, 5], [2, 4, 11], [6, 2, 10], [8, 6, 7], [9, 8, 1],
];

fn faces_share_edge(left: &[u8; 3], right: &[u8; 3]) -> bool {
    left.iter().filter(|vertex| right.contains(vertex)).count() == 2
}

fn face_adjacency() -> [[bool; 20]; 20] {
    let mut adjacency = [[false; 20]; 20];
    for left in 0..20 {
        for right in (left + 1)..20 {
            if faces_share_edge(&ICOSAHEDRON_FACES[left], &ICOSAHEDRON_FACES[right]) {
                adjacency[left][right] = true;
                adjacency[right][left] = true;
            }
        }
    }
    adjacency
}

/// Sort all faces by graph distance from `focus`, breaking ties by face ID.
fn face_bfs_order(focus: usize) -> [usize; 20] {
    debug_assert!(focus < 20);
    let adjacency = face_adjacency();
    let mut distances = [u8::MAX; 20];
    let mut queue = [0_usize; 20];
    let (mut head, mut tail) = (0_usize, 0_usize);
    distances[focus] = 0;
    queue[tail] = focus;
    tail += 1;
    while head < tail {
        let face = queue[head];
        head += 1;
        for neighbor in 0..20 {
            if adjacency[face][neighbor] && distances[neighbor] == u8::MAX {
                distances[neighbor] = distances[face] + 1;
                queue[tail] = neighbor;
                tail += 1;
            }
        }
    }
    debug_assert_eq!(tail, 20);
    let mut order = std::array::from_fn::<usize, 20, _>(|index| index);
    order.sort_by_key(|face| (distances[*face], *face));
    order
}

/// For each <=20-symbol chunk, restrict the canonical face order to local
/// indices that exist, then gather those symbols.
fn apply_lens_symbols(id: u8, input: &[u16]) -> Vec<u16> {
    let focus = (id - 20) as usize;
    let order = face_bfs_order(focus);
    let mut output = Vec::with_capacity(input.len());
    for chunk in input.chunks(20) {
        for local_index in order.iter().copied().filter(|index| *index < chunk.len()) {
            output.push(chunk[local_index]);
        }
    }
    output
}

/// Explicit local inverse: scatter each <=20-symbol chunk by the same
/// restricted BFS-distance+face-index order.
fn invert_lens_symbols(id: u8, input: &[u16]) -> Vec<u16> {
    let focus = (id - 20) as usize;
    let order = face_bfs_order(focus);
    let mut output = Vec::with_capacity(input.len());
    for chunk in input.chunks(20) {
        let mut restored = vec![0_u16; chunk.len()];
        let restricted = order.iter().copied().filter(|index| *index < chunk.len());
        for (stream_position, local_index) in restricted.enumerate() {
            restored[local_index] = chunk[stream_position];
        }
        output.extend_from_slice(&restored);
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    fn deterministic_payload(length: usize, salt: u64) -> Vec<u8> {
        let mut state = 0x9e37_79b9_7f4a_7c15_u64 ^ salt ^ length as u64;
        (0..length)
            .map(|index| {
                state ^= state << 13;
                state ^= state >> 7;
                state ^= state << 17;
                (state as u8)
                    .wrapping_add(index as u8)
                    .rotate_left((index % 8) as u32)
            })
            .collect()
    }

    fn deterministic_symbols(length: usize, bits: u8, salt: u64) -> Vec<u16> {
        let mask = (1_u16 << bits) - 1;
        let mut state = 0xd1b5_4a32_d192_ed03_u64 ^ salt ^ length as u64 ^ bits as u64;
        (0..length)
            .map(|index| {
                state ^= state << 13;
                state ^= state >> 7;
                state ^= state << 17;
                ((state as u16).wrapping_add(index as u16)) & mask
            })
            .collect()
    }

    fn sorted_bytes(mut bytes: Vec<u8>) -> Vec<u8> {
        bytes.sort_unstable();
        bytes
    }

    #[test]
    fn catalog_has_exact_shape_unique_ids_names_and_symmetric_inverses() {
        assert_eq!(OPERATORS.len(), 40);
        let mut names = HashSet::new();
        for (position, spec) in OPERATORS.iter().enumerate() {
            assert_eq!(spec.id as usize, position);
            assert!(names.insert(spec.name));
            let inverse = operator_spec(spec.inverse_id).unwrap();
            assert_eq!(inverse.inverse_id, spec.id);
            assert_eq!(inverse.family, spec.family);
        }
        assert_eq!(
            OPERATORS
                .iter()
                .filter(|spec| spec.family == Family::RnqC2xC2xC2)
                .count(),
            8
        );
        assert_eq!(
            OPERATORS
                .iter()
                .filter(|spec| spec.family == Family::SectorCyclic)
                .count(),
            12
        );
        assert_eq!(
            OPERATORS
                .iter()
                .filter(|spec| spec.family == Family::RadialLens)
                .count(),
            20
        );
        assert!(OPERATORS[..8]
            .iter()
            .all(|spec| spec.provenance == Provenance::InheritedExact));
        assert!(OPERATORS[8..]
            .iter()
            .all(|spec| spec.provenance == Provenance::NewComputational));
    }

    #[test]
    fn invalid_ids_fail_closed() {
        for id in 40_u8..=u8::MAX {
            assert_eq!(apply_operator(id, b"x"), Err(UnknownOperator(id)));
            assert_eq!(invert_operator(id, b"x"), Err(UnknownOperator(id)));
        }
    }

    #[test]
    fn floor_api_rejects_invalid_bits_and_out_of_range_symbols() {
        for bits in [0, 1, 5, 7, 9, 11, 13, 16] {
            assert_eq!(
                apply_symbols(0, bits, &[0]),
                Err(SymbolTransformError::InvalidFloorBits(bits))
            );
        }
        for bits in [6_u8, 8, 10, 12] {
            let value = 1_u16 << bits;
            assert_eq!(
                apply_symbols(0, bits, &[0, value]),
                Err(SymbolTransformError::SymbolOutOfRange {
                    index: 1,
                    value,
                    bits,
                })
            );
        }
        assert_eq!(
            apply_symbols(40, 8, &[0]),
            Err(SymbolTransformError::UnknownOperator(40))
        );
    }

    #[test]
    fn inherited_rnq_matches_exact_known_vectors() {
        let input = [0x01, 0x2d, 0x80, 0xf3];
        assert_eq!(apply_operator(0, &input).unwrap(), input);
        assert_eq!(apply_operator(1, &input).unwrap(), [0xf3, 0x80, 0x2d, 0x01]);
        assert_eq!(apply_operator(2, &input).unwrap(), [0x10, 0xd2, 0x08, 0x3f]);
        assert_eq!(apply_operator(4, &input).unwrap(), [0x08, 0x4b, 0x10, 0xfc]);
        assert_eq!(
            apply_operator(7, &input).unwrap(),
            input.iter().rev().map(|byte| byte.reverse_bits()).collect::<Vec<_>>()
        );
    }

    #[test]
    fn inherited_rnq_is_the_c2_cubed_xor_action() {
        for length in 0..=257 {
            let input = deterministic_payload(length, 0x524e51);
            for left in 0_u8..8 {
                for right in 0_u8..8 {
                    let composed = apply_operator(left, &apply_operator(right, &input).unwrap())
                        .unwrap();
                    assert_eq!(composed, apply_operator(left ^ right, &input).unwrap());
                }
            }
        }
    }

    #[test]
    fn floor_native_rnq_group_law_holds_at_6_8_10_12_bits() {
        for bits in [6_u8, 8, 10, 12] {
            for length in 0..=129 {
                let input = deterministic_symbols(length, bits, 0xc203_0000);
                for left in 0_u8..8 {
                    for right in 0_u8..8 {
                        let first = apply_symbols(right, bits, &input).unwrap();
                        let composed = apply_symbols(left, bits, &first).unwrap();
                        assert_eq!(
                            composed,
                            apply_symbols(left ^ right, bits, &input).unwrap()
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn every_operator_roundtrips_floor_symbols_at_all_four_widths() {
        for bits in [6_u8, 8, 10, 12] {
            for length in 0..=384 {
                let input = deterministic_symbols(length, bits, 0xf100_4000);
                for spec in OPERATORS {
                    let encoded = apply_symbols(spec.id, bits, &input).unwrap();
                    assert_eq!(encoded.len(), input.len());
                    assert_eq!(
                        invert_symbols(spec.id, bits, &encoded).unwrap(),
                        input,
                        "bits={} id={} length={}",
                        bits,
                        spec.id,
                        length
                    );
                }
            }
        }
    }

    #[test]
    fn byte_api_is_exactly_the_8_bit_floor_wrapper() {
        for length in 0..=512 {
            let input = deterministic_payload(length, 0x8b17);
            let symbols = input.iter().map(|value| *value as u16).collect::<Vec<_>>();
            for spec in OPERATORS {
                let byte_output = apply_operator(spec.id, &input).unwrap();
                let symbol_output = apply_symbols(spec.id, 8, &symbols).unwrap();
                assert_eq!(
                    byte_output,
                    symbol_output
                        .into_iter()
                        .map(|value| value as u8)
                        .collect::<Vec<_>>()
                );
            }
        }
    }

    #[test]
    fn every_operator_roundtrips_every_length_zero_through_1024() {
        for length in 0..=1024 {
            let payloads = [
                vec![0_u8; length],
                (0..length).map(|index| index as u8).collect(),
                deterministic_payload(length, 0xa5a5_5a5a),
            ];
            for input in &payloads {
                for spec in OPERATORS {
                    let encoded = apply_operator(spec.id, input).unwrap();
                    let restored = invert_operator(spec.id, &encoded).unwrap();
                    assert_eq!(restored, *input, "id={} length={}", spec.id, length);
                    assert_eq!(apply_operator(spec.id, input).unwrap(), encoded);
                }
            }
        }
    }

    #[test]
    fn boundary_lengths_roundtrip_all_operators() {
        let lengths = [1025, 2047, 2048, 4095, 4096, 8191, 8192, 16_381];
        for length in lengths {
            let input = deterministic_payload(length, 0xb0ad_a7e5);
            for spec in OPERATORS {
                let encoded = apply_operator(spec.id, &input).unwrap();
                assert_eq!(encoded.len(), input.len());
                assert_eq!(invert_operator(spec.id, &encoded).unwrap(), input);
            }
        }
    }

    #[test]
    fn sector_and_lens_operators_are_length_preserving_byte_permutations() {
        for length in 0..=521 {
            let input = deterministic_payload(length, 0x5ec7_0a);
            let expected = sorted_bytes(input.clone());
            for spec in &OPERATORS[8..] {
                let output = apply_operator(spec.id, &input).unwrap();
                assert_eq!(output.len(), input.len());
                assert_eq!(sorted_bytes(output), expected);
            }
        }
    }

    #[test]
    fn every_tri12_direction_has_an_explicit_computed_inverse() {
        for length in 0..=777 {
            let input = deterministic_payload(length, 0x1a2b_3c4d);
            for id in 8_u8..20 {
                let transformed = apply_operator(id, &input).unwrap();
                assert_eq!(invert_operator(id, &transformed).unwrap(), input);
            }
        }
    }

    #[test]
    fn tri12_uses_independent_chunks_and_exact_d_mod_chunk_length() {
        let input = (0_u8..29).collect::<Vec<_>>();
        for direction in 0_u8..12 {
            let output = apply_operator(8 + direction, &input).unwrap();
            let mut expected = input.clone();
            for chunk in expected.chunks_mut(12) {
                let shift = direction as usize % chunk.len();
                chunk.rotate_left(shift);
            }
            assert_eq!(output, expected);
        }
    }

    #[test]
    fn every_pi20_face_has_an_explicit_computed_inverse() {
        for length in 0..=4096 {
            let input = deterministic_payload(length, 0x1c05_a20);
            for id in 20_u8..40 {
                let gathered = apply_operator(id, &input).unwrap();
                assert_eq!(invert_operator(id, &gathered).unwrap(), input);
            }
        }
    }

    #[test]
    fn pi20_is_chunk_local_bfs_gather_with_restricted_face_indices() {
        let input = (0_u16..47).collect::<Vec<_>>();
        for focus in 0..20 {
            let order = face_bfs_order(focus);
            let mut expected = Vec::with_capacity(input.len());
            for chunk in input.chunks(20) {
                for local_index in order.iter().copied().filter(|index| *index < chunk.len()) {
                    expected.push(chunk[local_index]);
                }
            }
            let encoded = apply_symbols(20 + focus as u8, 6, &input).unwrap();
            assert_eq!(encoded, expected);
            assert_eq!(invert_symbols(20 + focus as u8, 6, &encoded).unwrap(), input);
        }
    }

    #[test]
    fn canonical_icosahedron_has_twenty_unique_faces_and_degree_three() {
        let mut canonical = HashSet::new();
        for mut face in ICOSAHEDRON_FACES {
            face.sort_unstable();
            assert!(canonical.insert(face));
        }
        let adjacency = face_adjacency();
        for face in 0..20 {
            assert_eq!(adjacency[face].iter().filter(|linked| **linked).count(), 3);
            assert!(!adjacency[face][face]);
            for other in 0..20 {
                assert_eq!(adjacency[face][other], adjacency[other][face]);
            }
        }
    }

    #[test]
    fn each_face_bfs_order_is_a_distance_then_face_id_permutation() {
        let adjacency = face_adjacency();
        for focus in 0..20 {
            let order = face_bfs_order(focus);
            let mut sorted = order;
            sorted.sort_unstable();
            assert_eq!(sorted, std::array::from_fn(|index| index));
            assert_eq!(order[0], focus);
            let mut distances = [u8::MAX; 20];
            distances[focus] = 0;
            for _ in 0..20 {
                for face in 0..20 {
                    for neighbor in 0..20 {
                        if adjacency[face][neighbor] && distances[face] != u8::MAX
                            && distances[neighbor] > distances[face] + 1 {
                            distances[neighbor] = distances[face] + 1;
                        }
                    }
                }
            }
            for window in order.windows(2) {
                assert!((distances[window[0]], window[0]) <= (distances[window[1]], window[1]));
            }
        }
    }

    #[test]
    fn singleton_is_fixed_by_all_operators() {
        for byte in 0_u8..=u8::MAX {
            for spec in OPERATORS {
                let transformed = apply_operator(spec.id, &[byte]).unwrap();
                let restored = invert_operator(spec.id, &transformed).unwrap();
                assert_eq!(restored, [byte]);
            }
        }
    }
}
