"""Scan every Git-indexed blob for public-repository boundary violations."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from asolaria_tournament.privacy import (
    FORBIDDEN_SUFFIXES,
    SKIP_SUFFIXES,
    forbidden_text_matches,
)

MAX_PUBLIC_BYTES = 2_000_000
ABSOLUTE_WINDOWS_PATH = re.compile(r"(?i)\b[A-Z]:[\\/]")
MACOS_USER_PATH = re.compile(r"/" + r"Users/[^/\s]+/")
MOUNTED_WINDOWS_PATH = re.compile(r"/" + r"mnt/[a-z]/", re.IGNORECASE)
PHYSICAL_DEVICE = re.compile(r"Physical" + r"Drive\d+", re.IGNORECASE)
ALLOWED_MODES = {"100644", "100755"}


def indexed_entries() -> list[tuple[str, str]]:
    process = subprocess.run(
        ["git", "ls-files", "-s", "-z"],
        cwd=ROOT,
        check=True,
        capture_output=True,
    )
    entries: list[tuple[str, str]] = []
    for raw_entry in process.stdout.split(b"\x00"):
        if not raw_entry:
            continue
        metadata, raw_path = raw_entry.split(b"\t", 1)
        mode = metadata.split(b" ", 1)[0].decode("ascii")
        path = raw_path.decode("utf-8")
        entries.append((mode, path))
    return entries


def main() -> int:
    failures: list[str] = []
    entries = indexed_entries()
    root_resolved = ROOT.resolve()
    for mode, relative in entries:
        if mode not in ALLOWED_MODES:
            failures.append(f"{relative}: forbidden git mode {mode}")
            continue
        path = (ROOT / relative).resolve()
        try:
            path.relative_to(root_resolved)
        except ValueError:
            failures.append(f"{relative}: path escapes repository")
            continue
        if not path.is_file():
            failures.append(f"{relative}: indexed blob missing from checkout")
            continue
        if path.suffix.lower() in FORBIDDEN_SUFFIXES:
            failures.append(f"{relative}: forbidden public suffix")
            continue
        if path.suffix.lower() in SKIP_SUFFIXES:
            failures.append(f"{relative}: generated bytecode is tracked")
            continue
        data = path.read_bytes()
        if len(data) > MAX_PUBLIC_BYTES:
            failures.append(f"{relative}: exceeds public artifact limit")
            continue
        if b"\x00" in data:
            failures.append(f"{relative}: unexpected binary blob")
            continue
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            failures.append(f"{relative}: tracked blob is not UTF-8")
            continue
        matches = forbidden_text_matches(text)
        matches.extend(
            label
            for label, pattern in (
                ("absolute_windows_path", ABSOLUTE_WINDOWS_PATH),
                ("macos_user_path", MACOS_USER_PATH),
                ("mounted_windows_path", MOUNTED_WINDOWS_PATH),
                ("physical_device", PHYSICAL_DEVICE),
            )
            if pattern.search(text)
        )
        for match in matches:
            failures.append(f"{relative}: privacy match {match}")

    for failure in failures:
        print(f"PUBLICTREEFAIL|message={failure}|json=0")
    ok = not failures
    print(
        f"PUBLICTREE|tracked={len(entries)}|findings={len(failures)}|"
        f"ok={int(ok)}|json=0"
    )
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
